/*
  File autogenerated by gengetopt version 2.22
  generated with the following command:
  gengetopt

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "generate a star-space-mass mapping";

const char *gengetopt_args_info_usage = "Usage: spacegen [OPTIONS]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help             Print help and exit",
  "  -V, --version          Print version and exit",
  "      --xmin=DOUBLE      minimum value for x  (default=`-20000.0')",
  "      --xmax=DOUBLE      maximum value for x  (default=`20000.0')",
  "      --ymin=DOUBLE      minimum value for y  (default=`-20000.0')",
  "      --ymax=DOUBLE      maximum value for y  (default=`20000.0')",
  "      --vxmin=DOUBLE     minimum value for vx  (default=`-20000.0')",
  "      --vxmax=DOUBLE     maximum value for vx  (default=`20000.0')",
  "      --vymin=DOUBLE     minimum value for vx  (default=`-20000.0')",
  "      --vymax=DOUBLE     maximum value for vy  (default=`20000.0')",
  "      --mass-min=DOUBLE  minimum value for the mass  (default=`1000.0')",
  "      --mass-max=DOUBLE  maximum value for the mass  (default=`2000.0')",
  "  -s, --star=INT         star count  (default=`35000')",
    0
};

typedef enum {ARG_NO
  , ARG_INT
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->xmin_given = 0 ;
  args_info->xmax_given = 0 ;
  args_info->ymin_given = 0 ;
  args_info->ymax_given = 0 ;
  args_info->vxmin_given = 0 ;
  args_info->vxmax_given = 0 ;
  args_info->vymin_given = 0 ;
  args_info->vymax_given = 0 ;
  args_info->mass_min_given = 0 ;
  args_info->mass_max_given = 0 ;
  args_info->star_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->xmin_arg = -20000.0;
  args_info->xmin_orig = NULL;
  args_info->xmax_arg = 20000.0;
  args_info->xmax_orig = NULL;
  args_info->ymin_arg = -20000.0;
  args_info->ymin_orig = NULL;
  args_info->ymax_arg = 20000.0;
  args_info->ymax_orig = NULL;
  args_info->vxmin_arg = -20000.0;
  args_info->vxmin_orig = NULL;
  args_info->vxmax_arg = 20000.0;
  args_info->vxmax_orig = NULL;
  args_info->vymin_arg = -20000.0;
  args_info->vymin_orig = NULL;
  args_info->vymax_arg = 20000.0;
  args_info->vymax_orig = NULL;
  args_info->mass_min_arg = 1000.0;
  args_info->mass_min_orig = NULL;
  args_info->mass_max_arg = 2000.0;
  args_info->mass_max_orig = NULL;
  args_info->star_arg = 35000;
  args_info->star_orig = NULL;

}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->xmin_help = gengetopt_args_info_help[2] ;
  args_info->xmax_help = gengetopt_args_info_help[3] ;
  args_info->ymin_help = gengetopt_args_info_help[4] ;
  args_info->ymax_help = gengetopt_args_info_help[5] ;
  args_info->vxmin_help = gengetopt_args_info_help[6] ;
  args_info->vxmax_help = gengetopt_args_info_help[7] ;
  args_info->vymin_help = gengetopt_args_info_help[8] ;
  args_info->vymax_help = gengetopt_args_info_help[9] ;
  args_info->mass_min_help = gengetopt_args_info_help[10] ;
  args_info->mass_max_help = gengetopt_args_info_help[11] ;
  args_info->star_help = gengetopt_args_info_help[12] ;

}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    {
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params =
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->xmin_orig));
  free_string_field (&(args_info->xmax_orig));
  free_string_field (&(args_info->ymin_orig));
  free_string_field (&(args_info->ymax_orig));
  free_string_field (&(args_info->vxmin_orig));
  free_string_field (&(args_info->vxmax_orig));
  free_string_field (&(args_info->vymin_orig));
  free_string_field (&(args_info->vymax_orig));
  free_string_field (&(args_info->mass_min_orig));
  free_string_field (&(args_info->mass_max_orig));
  free_string_field (&(args_info->star_orig));



  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, char *values[])
{
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->xmin_given)
    write_into_file(outfile, "xmin", args_info->xmin_orig, 0);
  if (args_info->xmax_given)
    write_into_file(outfile, "xmax", args_info->xmax_orig, 0);
  if (args_info->ymin_given)
    write_into_file(outfile, "ymin", args_info->ymin_orig, 0);
  if (args_info->ymax_given)
    write_into_file(outfile, "ymax", args_info->ymax_orig, 0);
  if (args_info->vxmin_given)
    write_into_file(outfile, "vxmin", args_info->vxmin_orig, 0);
  if (args_info->vxmax_given)
    write_into_file(outfile, "vxmax", args_info->vxmax_orig, 0);
  if (args_info->vymin_given)
    write_into_file(outfile, "vymin", args_info->vymin_orig, 0);
  if (args_info->vymax_given)
    write_into_file(outfile, "vymax", args_info->vymax_orig, 0);
  if (args_info->mass_min_given)
    write_into_file(outfile, "mass-min", args_info->mass_min_orig, 0);
  if (args_info->mass_max_given)
    write_into_file(outfile, "mass-max", args_info->mass_max_orig, 0);
  if (args_info->star_given)
    write_into_file(outfile, "star", args_info->star_orig, 0);


  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }

  return result;
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given,
               char *value, char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n",
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n",
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }


  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  int override;
  int initialize;
  int check_required;
  int check_ambiguity;

  package_name = argv[0];

  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "xmin",	1, NULL, 0 },
        { "xmax",	1, NULL, 0 },
        { "ymin",	1, NULL, 0 },
        { "ymax",	1, NULL, 0 },
        { "vxmin",	1, NULL, 0 },
        { "vxmax",	1, NULL, 0 },
        { "vymin",	1, NULL, 0 },
        { "vymax",	1, NULL, 0 },
        { "mass-min",	1, NULL, 0 },
        { "mass-max",	1, NULL, 0 },
        { "star",	1, NULL, 's' },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "hVs:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 's':	/* star count.  */


          if (update_arg( (void *)&(args_info->star_arg),
               &(args_info->star_orig), &(args_info->star_given),
              &(local_args_info.star_given), optarg, 0, "35000", ARG_INT,
              check_ambiguity, override, 0, 0,
              "star", 's',
              additional_error))
            goto failure;

          break;

        case 0:	/* Long option with no short option */
          /* minimum value for x.  */
          if (strcmp (long_options[option_index].name, "xmin") == 0)
          {


            if (update_arg( (void *)&(args_info->xmin_arg),
                 &(args_info->xmin_orig), &(args_info->xmin_given),
                &(local_args_info.xmin_given), optarg, 0, "-20000.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "xmin", '-',
                additional_error))
              goto failure;

          }
          /* maximum value for x.  */
          else if (strcmp (long_options[option_index].name, "xmax") == 0)
          {


            if (update_arg( (void *)&(args_info->xmax_arg),
                 &(args_info->xmax_orig), &(args_info->xmax_given),
                &(local_args_info.xmax_given), optarg, 0, "20000.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "xmax", '-',
                additional_error))
              goto failure;

          }
          /* minimum value for y.  */
          else if (strcmp (long_options[option_index].name, "ymin") == 0)
          {


            if (update_arg( (void *)&(args_info->ymin_arg),
                 &(args_info->ymin_orig), &(args_info->ymin_given),
                &(local_args_info.ymin_given), optarg, 0, "-20000.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "ymin", '-',
                additional_error))
              goto failure;

          }
          /* maximum value for y.  */
          else if (strcmp (long_options[option_index].name, "ymax") == 0)
          {


            if (update_arg( (void *)&(args_info->ymax_arg),
                 &(args_info->ymax_orig), &(args_info->ymax_given),
                &(local_args_info.ymax_given), optarg, 0, "20000.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "ymax", '-',
                additional_error))
              goto failure;

          }
          /* minimum value for vx.  */
          else if (strcmp (long_options[option_index].name, "vxmin") == 0)
          {


            if (update_arg( (void *)&(args_info->vxmin_arg),
                 &(args_info->vxmin_orig), &(args_info->vxmin_given),
                &(local_args_info.vxmin_given), optarg, 0, "-20000.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "vxmin", '-',
                additional_error))
              goto failure;

          }
          /* maximum value for vx.  */
          else if (strcmp (long_options[option_index].name, "vxmax") == 0)
          {


            if (update_arg( (void *)&(args_info->vxmax_arg),
                 &(args_info->vxmax_orig), &(args_info->vxmax_given),
                &(local_args_info.vxmax_given), optarg, 0, "20000.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "vxmax", '-',
                additional_error))
              goto failure;

          }
          /* minimum value for vx.  */
          else if (strcmp (long_options[option_index].name, "vymin") == 0)
          {


            if (update_arg( (void *)&(args_info->vymin_arg),
                 &(args_info->vymin_orig), &(args_info->vymin_given),
                &(local_args_info.vymin_given), optarg, 0, "-20000.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "vymin", '-',
                additional_error))
              goto failure;

          }
          /* maximum value for vy.  */
          else if (strcmp (long_options[option_index].name, "vymax") == 0)
          {


            if (update_arg( (void *)&(args_info->vymax_arg),
                 &(args_info->vymax_orig), &(args_info->vymax_given),
                &(local_args_info.vymax_given), optarg, 0, "20000.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "vymax", '-',
                additional_error))
              goto failure;

          }
          /* minimum value for the mass.  */
          else if (strcmp (long_options[option_index].name, "mass-min") == 0)
          {


            if (update_arg( (void *)&(args_info->mass_min_arg),
                 &(args_info->mass_min_orig), &(args_info->mass_min_given),
                &(local_args_info.mass_min_given), optarg, 0, "1000.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "mass-min", '-',
                additional_error))
              goto failure;

          }
          /* maximum value for the mass.  */
          else if (strcmp (long_options[option_index].name, "mass-max") == 0)
          {


            if (update_arg( (void *)&(args_info->mass_max_arg),
                 &(args_info->mass_max_orig), &(args_info->mass_max_given),
                &(local_args_info.mass_max_given), optarg, 0, "2000.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "mass-max", '-',
                additional_error))
              goto failure;

          }

          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:

  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
